### ISSUE TITLE
Assisted Setup OnPrem BC21 and this app

### ISSUE THREAD

**Issue by jefkeers** [Bertverbeek4PS/DataverseSyncUI#31]
Hi Bert,

When running the assisted setup of Dataverse to install it in a new onprem environment, we must be sure to not have installed the DataverseSyncUI app.  There is an event triggering on assisted setup which throws an error.

The Field does not exist. Identification fields and values: TableNo='0',No.='0'

Time stamp on error: 
2023-03-09T12:36:24.2015080Z

AL call stack: 
"Integration Table Mapping"(Table 5335)."Integration Table UID Fld. No. - OnValidate"(Trigger) line 5 - Base Application by Microsoft
"Integration Table Mapping"(Table 5335).CreateRecord line 10 - Base Application by Microsoft
"Integration Table Mapping"(Table 5335).CreateRecord line 11 - Base Application by Microsoft
**"Dataverse UI Events"(CodeUnit 70100).InsertIntegrationTableMapping line 2 - DataverseSyncUI by 4PS B.V.
"Dataverse UI Events"(CodeUnit 70100).HandleOnAfterResetConfiguration line 10 - DataverseSyncUI by 4PS B.V.**
"CDS Setup Defaults"(CodeUnit 7204).OnAfterResetConfiguration(Event) line 2 - Base Application by Microsoft
"CDS Setup Defaults"(CodeUnit 7204).SetCustomIntegrationsTableMappings line 2 - Base Application by Microsoft
"CDS Setup Defaults"(CodeUnit 7204).ResetConfiguration line 29 - Base Application by Microsoft
"CDS Connection Setup"(Table 7200).EnableIntegrationTables line 6 - Base Application by Microsoft
"CDS Connection Setup Wizard"(Page 7201).ConfigureCDSSolution - Base Application by Microsoft
"CDS Connection Setup Wizard"(Page 7201)."ActionFinish - OnAction"(Trigger) line 11 - Base Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).RunObject line 4 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).Run line 34 - System Application by Microsoft
"Guided Experience Impl."(CodeUnit 1991).Run line 16 - System Application by Microsoft
"Guided Experience"(CodeUnit 1990).Run line 2 - System Application by Microsoft
"CDS Connection Setup"(Page 7200)."Assisted Setup - OnAction"(Trigger) line 7 - Base Application by Microsoft

**Comment by Bertverbeek4PS** [comment]
Hi @jefkeers, sorry for my late reply.
Currently I'm out of the office.
But in the week of 20th of March I will look into the issue. I think I have got an idea.

**Comment by Bertverbeek4PS** [comment]
@jefkeers could you try again with the latest fix?
