### ISSUE TITLE
How can i add Sales line while sync Sales Header From Dataverse to BC?

### ISSUE THREAD

**Issue by samsiddiquiz** [Bertverbeek4PS/DataverseSyncUI#35]
How can i add Sales line while sync Sales Header From Dataverse to BC?

**Comment by Bertverbeek4PS** [comment]
You have to create two indvidual tables so sync to Dataverse.
It is not possible to combine those two tables into one migration.
If it is the posted header and lines you can have both lines.
Otherwise you have to skip the validation part of some fields.

**Comment by samsiddiquiz** [comment]
I have a requirement to synchronize unposted sales lines with the sales invoice details in Dataverse. However, I am confused because id do not have the document number and line number to map wth integration table. Could you please clarify how you can obtain this information?

**Comment by Bertverbeek4PS** [comment]
If the standard integration table hasn't got the fields that you needed you can always extend the standard table like a normal bc table.
I have Blogged about it:
https://www.bertverbeek.nl/blog/2022/02/16/extending-your-dataverse-sync-in-business-central/

This will help you?

**Comment by samsiddiquiz** [comment]
How can i update Dataverse Table Schema in business central ?
I have added new choice options in Dataverse invoice Table but that options is not coming in BC?

**Comment by Bertverbeek4PS** [comment]
You have to update also the procy table inside Business Central.
So if you have added options inside Dataverse those options must also be there inside Business Central.
You can extend it through an enum extensions only. Then you have the same options because the proxy table will read your enum values.

If it is an option in your own tables then you have to modify the optionmembers part.

**Comment by samsiddiquiz** [comment]
Thanks, can you please how I extend with enum that particular field? is there no way to update the schema of the table?

**Comment by Bertverbeek4PS** [comment]
If it is an enum you can extend it with an enum extension:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums#enumextension-object

**Comment by samsiddiquiz** [comment]
That field is not enum, this is the field 

![image](https://user-images.githubusercontent.com/32498803/236429020-273df288-8f95-4055-9b9c-6d468b5e9018.png)

**Comment by Bertverbeek4PS** [comment]
In which table is it?

**Comment by samsiddiquiz** [comment]
CRM Invoice

**Comment by Bertverbeek4PS** [comment]
I have seen the code. In BC we don;t have an field that is the same as the StatusCode field in Dataverse.
In the code it will zet the StatusCode based on some conditions. 
![image](https://user-images.githubusercontent.com/71499421/236451918-06252f32-87ad-4129-b7b5-08b814b7f198.png)
And there is no subscriber for it. 
So I think it will be hard to set the statusCode in Dataverse to another value.

**Comment by samsiddiquiz** [comment]
My question is how i get missing option value in business central?

**Comment by Bertverbeek4PS** [comment]
Well in Business Central you cannot add extra option to an excisting option.
That isn't possible.
That you only can do with enum and since this option isn;t an enum that isn;t possible.

**Comment by samsiddiquiz** [comment]
if I reset Dataverse integration?

**Comment by Bertverbeek4PS** [comment]
No that would not work to add the extra option.
The options are in the CRM invoice table and sayd before. It is hard coded.
